export const SAVE_BOX_INFO_SUCCESSFULLY = 'save_box_info'
export const GET_BOX_LIST_SUCCESSFULLY = 'get_box_list'
export const WAITING_FOR_RESPONSE = 'waiting_for_response'
export const ERROR_RECEIVED = 'error_received'

export const SUBMIT_BUTTON_PRESSED = 'submit_button_pressed'
export const VALIDATED_SUCCESSFULLY = 'validated_successfully'
export const VALIDATION_FAILED = 'validation_failed'
export const COLOUR_CHANGED = 'color_changed'
export const INPUT_CHANGED = 'input_changed'
export const NEGATIVE_WEIGHT_ENTERED = 'negative_weight_entered'